bibliotheque/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView, name='home'),
    path('register/', views.RegisterView, name='register'),
    path('list/', views.ListView, name='list'),
    path('detail/<id>', views.DetailView, name='detail'),
    path('carte/<id>', views.CarteView, name='carte'),
    path('pdf/', views.pdf, name='pdf'),
]

home/models.py
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw

SEXE = (
    ('homme', 'Homme'),
    ('femme', 'Femme'),
)

class Carte(models.Model):
    nom = models.CharField(max_length=100)
    postnom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    sexe = models.CharField(choices=SEXE, max_length=10)
    telephone = models.CharField(max_length=100)
    date_naissance = models.CharField(max_length=20)
    photo = models.ImageField(upload_to='photo/', blank=True)
    adresse = models.CharField(max_length=100)
    filiere = models.CharField(max_length=100, blank=True)
    promotion = models.CharField(max_length=100)
    
    email = models.CharField(max_length=100)
    lieu_naissance = models.CharField(max_length=50)

    annee_academique = models.CharField(max_length=100)
    nom_pere = models.CharField(max_length=100)
    contact_pere = models.CharField(max_length=100)
    nom_mere = models.CharField(max_length=100)
    contact_mere = models.CharField(max_length=100)
    nom_tuteur = models.CharField(max_length=100)
    contact_tuteur = models.CharField(max_length=100)

    nom_urgence = models.CharField(max_length=100)
    contact_urgence = models.CharField(max_length=100)

    qr_code = models.ImageField(upload_to="qr_code", blank=True)

    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.nom} {self.postnom} {self.prenom}'
    
    def save(self, *args, **kwargs):
        qr_image = qrcode.make(f"Nom: {self.nom}\nPost-nom: {self.postnom}\nPrenom: {self.prenom}\nTélephone: {self.telephone}\nFilière: {self.filiere}\nPromotion: {self.promotion}")
        canvas = Image.new('RGB', (qr_image.pixel_size, qr_image.pixel_size), 'white')
        draw = ImageDraw.Draw(canvas)
        canvas.paste(qr_image)
        file_name = f"qr_code-{self.nom}-{self.postnom}-{self.prenom}.png"
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        self.qr_code.save(file_name, File(buffer), save=False)
        canvas.close()
        return super().save(*args, **kwargs)

home/forms.py
from django import forms
from .models import Carte

class CarteForm(forms.ModelForm):
    class Meta:
        model = Carte
        fields = [
            'nom', 'postnom', 'prenom', 'email', 'sexe', 'telephone', 'date_naissance', 'lieu_naissance', 'adresse', 'photo',
            'promotion', 'annee_academique', 'nom_pere', 'contact_pere', 'nom_mere', 'contact_mere', 'nom_tuteur', 'contact_tuteur',
            'nom_urgence', 'contact_urgence', 'filiere',
        ]
        widgets = {
            'nom': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'postnom': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'prenom': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'email': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'sexe': forms.Select(attrs={'class': 'form-control mb-3'}),
            'telephone': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'date_naissance': forms.DateInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Ex: 12/05/2001'}),
            'adresse': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'filiere': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'promotion': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'photo': forms.FileInput(attrs={'class': 'form-control mb-3'}),

            'lieu_naissance': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'annee_academique': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'nom_pere': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'contact_pere': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'nom_mere': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'contact_mere': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'nom_tuteur': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'contact_tuteur': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'nom_urgence': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'contact_urgence': forms.TextInput(attrs={'class': 'form-control mb-3'}),
        }
        

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from .forms import CarteForm
from .models import Carte
from .pdf import makepdf
# from django_xhtml2pdf.utils import generate_pdf

def HomeView(request):
    template_name = 'home/index.html'
    return render(request, template_name)


def RegisterView(request):
    template_name = 'home/register.html'
    if request.method == "POST":
        form = CarteForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/list/')
        else:
            messages.error(request, "Données incorrectes! Réessayez")
            form = CarteForm()
            context = {
                'form': form,
            }
            return render(request, template_name, context)
    form = CarteForm()
    context = {
        'form': form,
    }
    return render(request, template_name, context)


def ListView(request):
    users = Carte.objects.all()
    template_name = 'home/list.html'
    context = {
        'users': users,
    }
    return render(request, template_name, context)


def DetailView(request, id):
    user = Carte.objects.get(id=id)
    template_name = 'home/detail.html'
    context = {
        'user': user,
    }
    return render(request, template_name, context)


def CarteView(request, id):
    user = Carte.objects.get(id=id)
    template_name = 'home/carte.html'
    context = {
        'user': user,
    }
    return render(request, template_name, context)


# def pdf(request):
#     pdf = makepdf("home/carte.html")
#     return HttpResponse(pdf, content_type="application/pdf")



from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

def pdf(request):
    # carte = Carte.objects.get(id=id)
    template_name = 'home/carte.html'
    # context = {'carte': carte}
    context = {}
    response = HttpResponse(content_type="application/pdf")
    response['Content-Disposition'] = 'attachment; filename="report.pdf"' 
    template = get_template(template_name)
    html = template.render(context)
    pdf = pisa.CreatePDF(html, dest=response)
    if pdf.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

templates/home/about.html
{% extends './base.html' %}
{% block content %}
        <main>
            <div class="container">
                <div class="row justify-content-between py-5 my-5">
                    <h1>A propos de l'application</h1>
                </div>
            </div>
        </main>
{% endblock %}

templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/slick-theme.css">
    <link rel="stylesheet" href="/static/css/slick.css">
    <link rel="stylesheet" href="/static/css/all.min.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/fonts.css">
    <title>Bibliothèque Medecine UNIKIN</title>
</head>
<body>
    <div class="wrapper">
        <header class="">
            <div class="container">
                <a href="{% url 'home:home' %}">
                <div class="d-flex py-3">
                    <img src="/static/img/unikin.png" width="50" alt=""> &nbsp;&nbsp;&nbsp;
                    <div class="left">
                        <h6>UNIKIN/Faculté de Medecine</h6>
                        <h6>Bibliothèque centrale</h6>
                    </div>
                </div>
                </a>
            </div>
        </header>

        {% block content %}{% endblock %}

        <footer>
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-auto">
                        <span>Powered by Get Skills Class.</span>
                    </div>
                    <div class="col-auto">
                        <span>&copy; copyright 2024 All Rigth Reserved to Braves Man TG</span> &nbsp;&nbsp;
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="/static/js/jquery-3.6.0.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/slick.min.js"></script>
    <script src="/static/js/html2canvas.min.js"></script>
    <script src="/static/js/script.js"></script>
</body>
</html>

templates/home/carte.html
{% extends './base.html' %}
{% block content %}
        <main>
            <div class="container mt-4">
                
                <div id="the-card" class="card-container mb-4">
                    <div class="row h-100 m-0">
                        <div class="col-6 left-side p-2 text-center">
                        </div>
                        <div class="col-6 right-side pt-3">
                        </div>
                        <div class="logo-container">
                            <img src="/static/img/logo-medecine.png" width="100" alt="">
                        </div>
                        <div class="row w-100 h-100 m-0 position-absolute text-container">
                            <div class="col-6 p-2 text-center">
                                <h5 class="m-0" style="font-size: 0.7rem;">REPUBLIQUE DEMOCRATIQUE DU CONGO</h5>
                                <p class="my-0" style="font-size: 0.5rem;">MINISTERE DE L'ENSEIGNEMENT SUPERIEURE ET UNIVERSITAIRE</p>
                                <h2 style="font-size: 1rem;">UNIVERSITE DE KINSHASA</h2>
                                <img src="/static/img/unikin.png" alt="unikin" width="40" height="40"> <br>
                                <img src="{{user.photo.url}}" alt="picture" width="100" height="100" style="float: left; margin-top: 20px; margin-left: 20px; object-fit: cover;">
                            </div>
    
                            <div class="col-6 pt-3">
                                <div class="d-flex flex-column align-items-center">
                                    <h6 class="text-white mb-1">{{user.nom}} {{user.postnom}}</h6>
                                    <span class="text-white">{{user.prenom}}</span>
                                    <hr class="mt-2 mb-1" style="height: 2px; width: 100px; background-color: rgb(248, 211, 0); opacity: 1; border-radius: 10px;">
                                    <span class="text-white">étudiant</span>
                                    <img src="{{user.qr_code.url}}" width="80" alt="qr_code">
                                </div>
                                <div class="d-block" style="margin-left: 17px; margin-top: 6px;">
                                    <strong class="text-white mb-1">Grade/Promotion : </strong> <span class="text-white">{{user.promotion}}</span> <br>
                                    <strong class="text-white mb-1">Dept./Filiaire : </strong> <span class="text-white">{{user.filiere}}</span> <br>
                                    <span class="text-white">{{user.telephone}}</span> <br>
                                    <span class="text-white">{{user.email}}</span> <br>
                                </div>
                            </div>
                        </div>

                        <div class="items">
                            <div class="item1"></div>
                            <div class="item2">
                                <i class="fa fa-phone-volume text-white d-block mb-1" style="font-size: 1.2rem;"></i>
                                <i class="fa fa-at text-white d-block mb-2" style="font-size: 1.2rem;"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <button id="download-btn" class="btn btn-success mb-4">Imprimer</button>
            </div>
        </main>

        <script>
            let btn = document.getElementById('download-btn');
            btn.addEventListener('click', function(){
                const screenTarget = document.getElementById('the-card');
                html2canvas(screenTarget).then((canvas)=>{
                    const base64image = canvas.toDataURL('image/png');
                    var anchor = document.createElement('a');
                    anchor.setAttribute('href', base64image)
                    anchor.setAttribute('download', 'mycard.png');
                    anchor.click();
                    anchor.remove();
                })
            })
        </script>
{% endblock %}

templates/home/detail.html
{% extends './base.html' %}
{% block content %}
        <main>
            <div class="container my-5">
                <h3>Fiche d'enregistrement</h3>
                <table class="table border my-4">
                    <tr>
                        <td>
                            <span>Nom</span>
                            <h6>{{user.nom}}</h6>
                        </td>
                        <td>
                            <span>Post-nom</span>
                            <h6>{{user.postnom}}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span>Prénom</span>
                            <h6>{{user.prenom}}</h6>
                        </td>
                        <td>
                            <span>Sexe</span>
                            <h6>{{user.sexe}}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span>Lieu de naissance</span>
                            <h6>{{user.lieu_naissance}}</h6>
                        </td>
                        <td>
                            <span>Date de naissance</span>
                            <h6>{{user.date_naissance}}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span>Téléphone</span>
                            <h6>{{user.telephone}}</h6>
                        </td>
                        <td>
                            <span>Email</span>
                            <h6>{{user.email}}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <span>Adresse</span>
                            <h6>{{user.adresse}}</h6>
                        </td>
                    </tr>
                </table>

                <table class="table border my-4">
                    <tr>
                        <td>
                            <span>Promotion</span>
                            <h6>{{user.promotion}}</h6>
                        </td>
                        <td>
                            <span>Année academique</span>
                            <h6>{{user.annee_academique}}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span>Nom du Père</span>
                            <h6>{{user.nom_pere}}</h6>
                        </td>
                        <td>
                            <span>Contact du Père</span>
                            <h6>{{user.contact_pere}}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span>Nom du Mère</span>
                            <h6>{{user.nom_mere}}</h6>
                        </td>
                        <td>
                            <span>Contact du Mère</span>
                            <h6>{{user.contact_mere}}</h6>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span>Nom du Tuteur</span>
                            <h6>{{user.nom_tuteur}}</h6>
                        </td>
                        <td>
                            <span>Contact du Tuteur</span>
                            <h6>{{user.contact_tuteur}}</h6>
                        </td>
                    </tr>
                </table>

                <table class="table border my-4">
                    <tr>
                        <td>
                            <span>Noms de la personne à contacter en cas d'urgence</span>
                            <h6>{{user.nom_urgence}}</h6>
                        </td>
                        <td>
                            <span>Contact</span>
                            <h6>{{user.contact_urgence}}</h6>
                        </td>
                    </tr>
                </table>

                <table class="table border my-4">
                    <tr>
                        <td>
                            <span>Code QR</span>
                            {% if user.qr_code %}
                            <img src="{{user.qr_code.url}}" class="d-block mt-1" width="100" alt="qr_code">
                            {% endif %}
                        </td>
                        <td>
                            <span>Date</span>
                            <h6>Le {{user.date|date:'d/m/Y'}}</h6>
                        </td>
                    </tr>
                </table>
            </div>
        </main>
        
        <script></script>
{% endblock %}

templates/home/index.html
{% extends './base.html' %}
{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-between py-3">
                <div class="col-md-4">
                    <div class="btns text-center m-3">
                        <button id="circle-btn" class="circle text-center">
                            <h3>Nouvel <br> enregistrement</h3>
                        </button>
                            <a href="{% url 'home:list' %}" class="btn btn-success">Liste des enregistrements</a> <br>
                    </div>
                </div>

                <div class="col-md-4 mt-5">
                    <div id="carouselId" class="carousel slide h-75" data-bs-ride="carousel">
                        <div class="carousel-item active">
                            <div class="details mt-5">
                                <h5>Welcome to get register !</h5>
                                <span>Nous avons mis en place des mesures <br>strictes pour protéger vos données et <br>garantir la securité de l'application, <br>l'accès securisé, des mises à jour régulières et la <br> formation du personnel. <br>Merci de votre confiance!</span>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="details mt-5">
                                <h5>Pour commencer, cliquez sur</h5>
                                <button class="btn btn-info">Nouvel enregistrement</button>
                            </div>
                        </div>
                    </div>

                    <div class="text-center">
                        <a href="about.html" class="btn btn-primary about-btn">A propos</a>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="pub">
                        <div class="content">
                            <img src="/static/img/ruben.jpg" alt="ruben">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="choiceBanner" class="d-none">
            <div class="d-flex flex-column">
                <h4 class="mb-4">Choisissez un enregistrement</h4>
                <a href="{% url 'home:register' %}" class="btn btn-info etud">
                    Enregistrer un étudiant
                </a>
                <a href="{% url 'home:register' %}" class="btn btn-primary pers">
                    Enregistrer un personnel
                </a>
                <button id="closeBanner" class="btn btn-danger w-100">Annuler</button>
            </div>
        </div>
    </main>

    <script>
        let circleBtn = document.getElementById('circle-btn');
        let choiceBanner = document.getElementById('choiceBanner');
        let closeBanner = document.getElementById('closeBanner');
        circleBtn.addEventListener('click', ()=>{
            choiceBanner.classList.toggle('d-none')
        })
        closeBanner.addEventListener('click', ()=>{
            choiceBanner.classList.toggle('d-none')
        })
    </script>
{% endblock %}

templates/home/list.html
{% extends './base.html' %}
{% block content %}
        <main>
            <div class="container mt-4">
                <h3>Liste d'enregistrements</h3>
                <table class="table border">
                    <tr>
                        <td>Photo</td>
                        <td>Nom</td>
                        <td>Post-nom</td>
                        <td>Prénom</td>
                        <td>Sexe</td>
                        <td>Email</td>
                        <td>Téléphone</td>
                        <td>Lieu de naissance</td>
                        <td>Date de naissance</td>
                        <td>Adresse</td>
                        <td>Voir</td>
                    </tr>
                    {% for user in users %}
                    <tr>
                        <td class="pb-3">
                            <img src="{{user.photo.url}}" width="50" alt="{{user.nom}}">
                        </td>
                        <td class="pb-3">{{user.nom}}</td>
                        <td class="pb-3">{{user.postnom}}</td>
                        <td class="pb-3">{{user.prenom}}</td>
                        <td class="pb-3">{{user.sexe}}</td>
                        <td class="pb-3">{{user.email}}</td>
                        <td class="pb-3">{{user.telephone}}</td>
                        <td class="pb-3">{{user.lieu_naissance}}</td>
                        <td class="pb-3">{{user.date_naissance}}</td>
                        <td class="pb-3">{{user.adresse}}</td>
                        <td class="pb-3">
                            <a href="{% url 'home:carte' user.id %}" class="btn btn-info py-1 mt-2">Voir la carte</a>
                            <a href="{% url 'home:detail' user.id %}" class="btn btn-primary py-1 mt-2">Voir la fiche</a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </main>
{% endblock %}

templates/home/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/css/bootstrap-icons/bootstrap-icons.min.css">
    <link rel="stylesheet" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/style.css">
    <title>Bibliothèque Medecine UNIKIN</title>
</head>
<body>
    <div class="wrapper">
        <div class="text-center mt-5 mb-3">
            <h4>UNIKIN/FACULTE DE MEDECINE</h4>
            <h4>BIBLIOTHEQUE CENTRALE</h4>
        </div>

        <main>
            <form action="index.html" class="log-form">
                <h4 class="mb-3">Connexion</h4>
                <label for="email">
                    Adresse email
                    <input type="email" name="email" id="email" class="form-control">
                </label>
                <label for="email">
                    Mot de passe
                    <input type="password" name="password" id="password" class="form-control">
                </label>
                <button type="submit" class="btn btn-success">Se connecter</button>
            </form>
        </main>

    <script src="static/js/bootstrap.bundle.min.js"></script>
    <script src="static/js/script.js"></script>
</body>
</html>

templates/home/register.html
{% extends './base.html' %}
{% block content %}
        <main class="mt-3">
            <h5 class="mb-3 text-center">FICHE D'IDENTIFICATION POUR LA BIBLIOTHEQUE/ETUDIANT</h4>
            <hr class="my-2">
            <form method="post" enctype="multipart/form-data" class="log-form mb-5">
                {% if messages %}
                {% for message in messages %}
                <small class="text-danger">{{message}}</small>
                {% endfor %}
                {% endif %}
                {% csrf_token %}
                <div id="first">
                    <label for="">
                        Nom
                        {{form.nom}}
                    </label>
                    <label for="">
                        Post-nom
                        {{form.postnom}}
                    </label>
                    <label for="">
                        Prenom
                        {{form.prenom}}
                    </label>
                    <label for="">
                        Sexe
                        {{form.sexe}}
                    </label>
                    <label for="">
                        Date de naissance
                        {{form.date_naissance}}
                    </label>
                    <label for="">
                        Téléphone
                        {{form.telephone}}
                    </label>
                    <label for="">
                        Adresse
                        {{form.adresse}}
                    </label>
                    <label for="">
                        Promotion
                        {{form.promotion}}
                    </label>
                    <label for="">
                        Filière
                        {{form.filiere}}
                    </label>
                    <label for="">
                        Photo
                        {{form.photo}}
                    </label>
                    <button id="next-btn" class="btn btn-info mt-2 px-5">Suivant</button>
                </div>

                <div id="last" class="d-none">
                    <label for="">
                        Email
                        {{form.email}}
                    </label>
                    <label for="">
                        Lieu de naissance
                        {{form.lieu_naissance}}
                    </label>
                    <label for="">
                        Année academique
                        {{form.annee_academique}}
                    </label>
                    <label for="">
                        Nom du Père
                        {{form.nom_pere}}
                    </label>
                    <label for="">
                        Contact du Père
                        {{form.contact_pere}}
                    </label>
                    <label for="">
                        Nom de la Mère
                        {{form.nom_mere}}
                    </label>
                    <label for="">
                        Contact de la Mère
                        {{form.contact_mere}}
                    </label>
                    <label for="">
                        Nom du Tuteur
                        {{form.nom_tuteur}}
                    </label>
                    <label for="">
                        Contact du Tuteur
                        {{form.contact_tuteur}}
                    </label>
                    <label for="">
                        Nom d'urgence
                        {{form.nom_urgence}}
                    </label>
                    <label for="">
                        Contact d'urgence'
                        {{form.contact_urgence}}
                    </label>
                    <button type="submit" class="btn btn-success px-5">Enregistrer</button>
                </div>
            </form>
        </main>
        
    <script>
        let first = document.getElementById('first');
        let last = document.getElementById('last');
        let next = document.getElementById('next-btn');
        next.addEventListener('click', ()=>{
            first.classList.toggle('d-none')
            last.classList.toggle('d-none')
        })
    </script>
{% endblock %}